### PR TITLE
Dnsim codegen

### PR DESCRIPTION
**Pull request by kupiqu**
Four things are in this pull request to the dev branch:
1. I introduced a parms.debug to help debugging why codegen failed to generate a mex file when that is the case, so this debug option avoids deleting the odefun m function.
2. Cleaning things up: codemex directory is removed after the mex file generation and same for params.mat after running the simulation.
3. I renamed coder by parms.coder in runsim.m and dnsimulator.m
4. I removed from odefun script all the instances of t=T(k-1). This is not used anywhere besides currents like the Poisson input that don't have state variables. In those cases, we can just use:

`Gt(k) = g_ext.*G(:,max(1,k-1)); % k refers to time steps, where k-1 is t=0`

### CODE REVIEW

**Comment by jsherfey** [comment]
't' needs to be defined in the odefun script to support mechanisms with explicit time-dependence. For instance, external inputs may need it for turning on and off. This could be achieved with an index as well, but that index would need to be adjusted every time dt changes. A possibly more serious issue is that t needs to be defined in order to support systems that are not autonomous.

**Comment by kupiqu** [comment]
I don't see why it needs to be adjusted. If you use index k, then in odefun that input operates exactly as the other state variables.

Anyways, we can chat tomorrow if you are around to clarify this further...

**Comment by jsherfey** [comment]
What I had in mind is like this --

V' = Iext*(t>100 & t<200)   % apply external input from 100-200ms

V' = f(V) + t   % non-autonomous function

It's not clear to me how to integrate the latter without explicitly
defining t in the odefun script. The former seems to be simplified by
having t defined explicitly (instead of requiring the user to define
V'=Iext*(k>(100/dt) & k<(200/dt))).

**Comment by kupiqu** [comment]
Perhaps we can do it internally in dnsim, so we don't bother the user (which I agree we shouldn't). Wherever dnsim finds t, change it by k-1... (normalized by dt, of coarse)

**Comment by jsherfey** [comment]
That might work, let's discuss it tomorrow.

Did you find that removing t=T(k-1) sped up the simulation significantly?
Also, did eliminating double indices in state variables make a big
difference ( m(i) instead of m(i,1) )?

**Comment by kupiqu** [comment]
Well, I actually wanted to test whether any of the three  m(i),  m(i,1) or m(1,i) showed an improvement compared to the default vectorial notation, and this didn't happen neither in JIT nor in codegen (but the opposite, due to the additional for that is required), so I just came back to our default.

Regarding the t thing. Well, it is not much benefit now, as it was reduced to just one line of code inside the for (I went optimizing this with several steps, and today I realized that it could be completely removed). I would still do it for the sake of optimization, as this one line gets repeated hundreds of thousands of times for a typical simulation, and can be quite easily avoided. In fact, the resulting odefun would also be more coherent, so all terms that are within the for are in the same 'time units': "k".

**Pull request merged**
